### ISSUE TITLE
Referenceing to site root

### ISSUE THREAD

**Issue by victorzzt** [decko-commons/decko#150]
This is more like a feature request.

When using reverse proxy not having access to siteroot (organizational limitation)
The webpage trying to access <siteroot>/files and <siteroot>/assets

Is it possible to change to relative address

**Comment by ethn** [comment]
Here's the relevant Rails documentation for how to do that: http://guides.rubyonrails.org/configuring.html#deploy-to-a-subdirectory-relative-url-root

Short version, you have some options:
config.relative_url_root = "/decko" (eg in config/application.rb)
RAILS_RELATIVE_URL_ROOT = "/decko" (as an environmental variable)
in your passenger configuration (.htaccess): RackBaseURI = "/decko"
