### ISSUE TITLE
Decko optimalizations

### ISSUE THREAD

**Issue by tukanos** [decko-commons/decko#161]
Hi Ethan,

Is this still valid from the [wagn.org](http://wagn.org/get_started) site?

> Optimizing
> 
>  
> 
> The above should help you get wagn working, but you'll have to do a bit more to make it fast.
> 
>     memcache. This is vital for a high-performing Wagn site.
> 
>     To configure wagn for memcache, add this to your Gemfile:
> 
>     gem 'dalli'
> 
>     and edit config/application.rb with the following:
> 
>     config.cache_store = :dalli_store, []
> 
>     mod_xsendfile. File and Image cards process permissions before sending the file.  This makes that fast.
>     mod_expires. Makes use of wagn's non-expiring assets so images, stylesheets, and javascript don't slow down page loads at all.
>     You'll need to enable mod_headers so that the ht_access will work (Headers directives)
>     Also, you'll need to symlink to the gem's public directory if you're running a version older than 1.13 This should happen automatically whenever you run `wagn update`, but you can also do it manually using `rake wagn:update_assets_symlink
> 
>     As of wagn 1.13.0 this is no longer needed, but might still be relevant to some users:
>     You will need to pay special attention to the public directory.  Because Wagn is still transitioning its javascript into cards, it is still using the public directory from the Wagn gem and not from the individual Wagn installation.  The temporary fix for this is to create a symbolic link to the gem's public directory. 
>     So if you created a new wagn in /srv/mywagn, let's call that's your "appdir".   And if your wagn gem is stored in /usr/local/rvm/gems/ruby-1.9.3-p374/gems/wagn-1.12.12, that would be your "gemdir".  You can find out where your wagn gem is located using `bundle show wagn`.  The public directory link you need is something like this:
> 
>      
> 
>     > cd [appdir]; ln -s [gemdir]/public

**Comment by ethn** [comment]
Yes, number 1-4 are still strongly recommended.

`xsendfile` is not needed if you host files/images on the cloud, but if you host them locally it's quite valuable.
