### ISSUE TITLE
[security]Two factor authorization 

### ISSUE THREAD

**Issue by tukanos** [decko-commons/decko#166]
Hi Ethan,

I wonder if you ever setup *Decko* with two-factor authorization.  Do you have thoughts on this?

**Comment by ethn** [comment]
I haven't ever set that up, no, though I'd like that to be an option.

Broadly speaking, our development priorities fall into two categories:
1. Things that WikiRate.org needs (because they are funding Decko's development)
2. Things that support other developers in extending Decko. (because that's how we see Decko building capacity/scope/scale)

I don't think WikiRate.org is going to be all that interested in 2-factor authorization for a little while, but it may become more valued once there is an emphasis on verified company accounts.

In the meantime, I doubt we'd find space to make that feature a particular priority, but if any other developer wanted to work on it, supporting Decko developers _is_ a high priority for us.

And, generally speaking, I'd like to see a lot more authentication options for decko!

**Comment by tukanos** [comment]
> Things that WikiRate.org needs (because they are funding Decko's development)

Those are, of course, the most important as you want to continue fund your development.  By the way, congratulations on finding a sponsor.  It is rather hard to do.

> Things that support other developers in extending Decko. (because that's how we see Decko building capacity/scope/scale)

Yes that is what I see too.  If you have bunch of developers wanting to write plugins or new functionality you have won in the long run.

> I don't think WikiRate.org is going to be all that interested in 2-factor authorization for a little while, but it may become more valued once there is an emphasis on verified company accounts.

There is actually a reason why I'm asking.  I know one guy who is exploring ways how to break the SSL encryption.  His work is under NDA so I don't know the details, but since he started to look for two-factor authentications as he stated "the SSL is not enough anymore".  I take him seriously as he is really good at what he is doing.

> In the meantime, I doubt we'd find space to make that feature a particular priority, but if any other developer wanted to work on it, supporting Decko developers is a high priority for us.

Is [this](http://wagn.org/mods) still accurate information?  I'm now busy learning Smalltalk but would love to help you in the long run if I should have more time on my hands.

**Comment by ethn** [comment]
[The mods page](http://wagn.org/mods) was pretty outdated, but you inspired me to update it (including with links to the code documentation, which is far more current).

It would be fantastic if you were interesting in helping out. There's been so much focus on WikiRate lately that it feels like we've done very little to support community. On the other hand, looking at that old mod documentation reminds me that we've made huge strides as a development platform and have a lot more to offer now. But we haven't really gotten the documentation to the point where it can really teach mod development soup to nuts. You've clearly a clear thinker about documentation/communication, so if you were learning to develop mods and helping us find and fill holes in the docs and start creating better ways to share mods, for example, that in itself would be a huge help.

**Comment by tukanos** [comment]
Thank you for update.

> You've clearly a clear thinker about documentation/communication
Hahaha,  actually I really hate to document anything ;).  However, for one being outside the development process the documentation is the only thing, outside the code itself, with which you can save plenty of time.

> if you were learning to develop mods and helping us find and fill holes in the docs and start creating better ways to share mods, for example, that in itself would be a huge help.
Yes, I tend to create a documentation for myself so I don't have to relearn it and I have place to check.  I'll then share steps how to develop a mod for Decko then.

**Comment by ethn** [comment]
Nice!

To be clear, I'm not trying to unload a bunch of documentation tasks on you. But it's just a lot easier (and more meaningful) to write docs in collaboration with someone who's actually using them, giving feedback on the vital things that are missing, and willing to make the occasional leap across the void!
