### ISSUE TITLE
[link] Dead link to Workflow Howto

### ISSUE THREAD

**Issue by tukanos** [decko-commons/decko#167]
Hi Ethan,

I'm looking around how to setup Decko in a way that would not require too much change after initial setup.  First approach is to go via the links and I found out that the [workflow link](http://wagn.org/Deckering) is dead or was not yet created (same with Evolution).   What is the correct link?

Thank you

**Comment by ethn** [comment]
I can't seem to find the source of that dead link, but "Deckering" sounds like an attempt at an update to what we used to call "Wagneering", so the intended link is probably http://wagn.org/wagneering?

**Comment by tukanos** [comment]
Probably yes.  As the I take the Decko and Wagn terms as synonyms.

I see you have created the Deckering card already:

Before it was:
![image](https://user-images.githubusercontent.com/731154/36417243-ac02b782-162b-11e8-9337-51ee3ab6a0de.png)

Now it is empty:

![image](https://user-images.githubusercontent.com/731154/36417259-b4571d4c-162b-11e8-9767-63d85f7481d9.png)

Here you can find the bogus links:

![image](https://user-images.githubusercontent.com/731154/36417299-d7881bfe-162b-11e8-9b6a-77d59b42084f.png)

**Comment by ethn** [comment]
Fixed here: https://github.com/decko-commons/decko-seed/commit/3fc802b289370eb12dd42b031c40ceb81a71be4d

Will be included in next release.  Thank you!!!
