### ISSUE TITLE
translation missing: en.mod.card-mod-format-0.11.1.set.type.toggle.no

### ISSUE THREAD

**Issue by bertdeb** [decko-commons/decko#613]
Brand-new deck. If I create a new card `newcard` and set its type to **Toggle**, it displays the following when I save it:
`translation missing: en.mod.card-mod-format-0.11.1.set.type.toggle.no`

Similarly, if I delete it and create a new 'newcard' and set its type to **Image** without adding an image file, on submit I get the following:
```
translation missing: en.mod.card-mod-format-0.11.1.set.all.html_error.problems_name

IMAGE: is missing
```
If I attempt to add an image, I get:

`Imagefile.png | 8.93 KB |  translation missing: en.mod.card-mod-carrierwave-0.11.1.set.type.file.delete`

Similarly, delete it and create new 'newcard' and set its type to **Search** and try to **Submit** it empty:
```
translation missing: en.mod.card-mod-format-0.11.1.set.all.html_error.problems_name

CORE VIEW: can't run search with empty content
```
Delete that, new card 'newcard' and set its type to **CardType**:
 ```
+description
translation missing: en.mod.card-mod-format-0.11.1.set.type.cardtype.add_card
   translation missing: en.mod.card-mod-format-0.11.1.set.type.cardtype.configure_card
0 results
```

**Comment by ethn** [comment]
Yikes, I clearly missed a lot of translations when I was moving code between mods. I'm hoping to get all of these fixed today and make sure they are covered in our test suite.

Very grateful that you're taking the time to let us know about all these.

**Comment by ethn** [comment]
OH, no, I get it now. It's sticking the version in the locales scope.  Fixing...

**Comment by ethn** [comment]
(This is another issue that only shows up when using the gems.)

**Comment by ethn** [comment]
Sorry so slow on this. Just put out 0.11.2, which fixes these localization issues.
